" --- sensible defaults ---
set nocompatible
filetype plugin indent on
syntax on

set number
set hidden
set mouse=a
set clipboard=unnamed

" --- indentation (tabs -> spaces) ---
set expandtab
set shiftwidth=2
set tabstop=2
set softtabstop=2
set smartindent

" --- nice editing ---
set nowrap
set linebreak
set breakindent
set undofile
set ignorecase
set smartcase
set incsearch
set hlsearch

" --- visuals ---
set termguicolors
set cursorline
set signcolumn=yes

" --- extras ---
" keep a bit of context above/below the cursor
set scrolloff=5
set sidescrolloff=5

" cursor goes to new window
set splitbelow
set splitright

" sensible per-language indentation overrides
autocmd FileType python,go setlocal shiftwidth=4 tabstop=4 softtabstop=4
autocmd FileType make setlocal noexpandtab

" command completion more like bash
set wildmode=longest:full,full
